#
# MBDyn (C) is a multibody analysis code.
# http://www.mbdyn.org
#
# Copyright (C) 1996-2002
#
# Pierangelo Masarati     <masarati@aero.polimi.it>
# Paolo Mantegazza        <mantegazza@aero.polimi.it>
#
# Dipartimento di Ingegneria Aerospaziale - Politecnico di Milano
# via La Masa, 34 - 20156 Milano, Italy
# http://www.aero.polimi.it
#
# Changing this copyright notice is forbidden.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation (version 2 of the License).
# 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# You don't need to modify this file; you may list extra dependencies 
# (besides 'module-XXX.cc') in var 'MODULE_DEPENDENCIES' in file 
# module-XXX/Makefile.inc

-include Makefile.inc

.PHONY: all clean

all: $(MBDYN_MODULE).so

$(MBDYN_MODULE).so: $(MODULE_DEPENDENCIES) $(MBDYN_MODULE).o 
	$(CXXLINK) -o $@ $^

.cc.o:
	$(LTCXXCOMPILE) -c $<

.c.o:
	$(LTCOMPILE) -c $<

.f.o:
	$(LTF77COMPILE) -c $<

clean:
	-rm -f *.o core

distclean: clean
	-rm -rf *.lo *.so .libs

