# $Header$
# MBDyn (C) is a multibody analysis code.
# http://www.mbdyn.org
#
# Copyright (C) 1996-2015
#
# Pierangelo Masarati     <masarati@aero.polimi.it>
# Paolo Mantegazza        <mantegazza@aero.polimi.it>
#
# Dipartimento di Ingegneria Aerospaziale - Politecnico di Milano
# via La Masa, 34 - 20156 Milano, Italy
# http://www.aero.polimi.it
#
# Changing this copyright notice is forbidden.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation (version 2 of the License).
# 
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# You don't need to modify this file; you may list extra dependencies 
# (besides 'module-XXX.cc') in var 'MODULE_DEPENDENCIES' in file 
# module-XXX/Makefile.inc

-include $(MBDYN_MODULE_SRCDIR)/Makefile.inc

.PHONY: all clean clean-so

all: lib$(MBDYN_MODULE).la

lib$(MBDYN_MODULE).la: $(MODULE_DEPENDENCIES) $(MBDYN_MODULE).lo 
	rm -f $@
	$(CXXLINK) -rpath $(LIBEXEC_DIR) -o $@ $^ $(MODULE_LINK)

%.lo: %.cc
	$(MAKE) clean-so
	$(LTCXXCOMPILE) -o $@ -I$(MBDYN_MODULE_SRCDIR) $(MODULE_INCLUDE) -DMBDYN_MODULE -c $<

%.lo: %.c
	$(MAKE) clean-so
	$(LTCOMPILE) -o $@ -I$(MBDYN_MODULE_SRCDIR) $(MODULE_INCLUDE) -DMBDYN_MODULE -c $<

%.lo: %.f90
	$(MAKE) clean-so
	$(LTFCCOMPILE) -o $@ -I$(MBDYN_MODULE_SRCDIR) -DMBDYN_MODULE -c $<

%.lo: %.f95
	$(MAKE) clean-so
	$(LTFCCOMPILE) -o $@ -I$(MBDYN_MODULE_SRCDIR) -DMBDYN_MODULE -c $<

%.lo: %.f
	$(MAKE) clean-so
	$(LTF77COMPILE) -o $@ -DMBDYN_MODULE -c $<

install: lib$(MBDYN_MODULE).la
	if test -f $<; then \
		$(LIBTOOL) --mode=install $(INSTALL_PROGRAM) $< $(LIBEXEC_DIR)/$< ; \
	fi

clean:
	-rm -f *.o *.lo core

clean-so:
	-rm -f *.so

distclean: clean
	-rm -rf *.lo *.so .libs

