## $Header$
MODULE_LINK=-L/home/masarati/Lavoro/mbdyn/leapmotion/LeapDeveloperKit_2.2.2+24469_linux/LeapSDK/lib/x64 -lLeap

# FIXME: this flag is needed by g++ 4.8 to include <cstdint>
MODULE_INCLUDE=-I/home/masarati/Lavoro/mbdyn/leapmotion/LeapDeveloperKit_2.2.2+24469_linux/LeapSDK/include -std=c++0x
