## $Header$
#MODULE_DEPENDENCIES=
#LIBPATH=/usr/lib/octave-3.2.4/
#LIBPATH=/usr/lib/debug/usr/lib/octave-3.2.4/
#MODULE_LINK=-L$(LIBPATH) -Wl,-rpath=$(LIBPATH) -loctinterp -loctave # -lcruft
#MODULE_LINK=-loctinterp -loctave # -lcruft

#MODULE_INCLUDE=-I/home/masarati/Lavoro/mbdyn/bullet-2.72/src/
MODULE_INCLUDE=-I/usr/include/bullet/
MODULE_LINK=-lBulletCollision
