All: sfun_mbdyn_com_read.mexglx sfun_mbdyn_com_write.mexglx sfun_mbdyn_start.mexglx

sfun_mbdyn_com_read.mexglx : sfun_mbdyn_com_read.c
		mex sfun_mbdyn_com_read.c
sfun_mbdyn_com_write.mexglx : sfun_mbdyn_com_write.c
		mex sfun_mbdyn_com_write.c
sfun_mbdyn_start.mexglx : sfun_mbdyn_start.c
		mex sfun_mbdyn_start.c

clean:
		rm -f *.mexglx
