# $Header$
###############################################################################
#
# Add module dependencies here; e.g., if in dir 'module-X' there's 
# a file 'myfunc.cc' write:
#
# MODULE_DEPENDENCIES=myfunc.o
#
# Then put this file in directory 'module-X' as 'Makefile.inc'
#
###############################################################################

MODULE_DEPENDENCIES=diffsizes.o hydrodynamic_plain_bearing_force.o hydrodynamic_plain_bearing_force_dv.o

